apiVersion: v1
kind: ReplicationController
metadata:
   name: myapp-rc
spec:
   replicas: 3
   selector: 
     app: myapp
     version: 4.2.14

   template:
     metadata:
       labels:
          app: myapp
          version: 4.2.14

     spec:
       containers:
       - name: mycon1
         image: maha4iac/myonlinebooking:1
         ports:
          - containerPort: 8080