apiVersion: v1
kind: Service
metadata:
   name: myapp-svc
   labels:
     app: myapp
     version: 4.2.14
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30030
  selector:
     app: myapp
     version: 4.2.14